# Generated by Django 5.1.4 on 2026-06-11 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('original_filename', models.CharField(max_length=512, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'Обрабатывается'), ('extracted', 'Извлечён'), ('done', 'Готов'), ('failed', 'Ошибка')], default='uploaded', max_length=16, verbose_name='Статус')),
                ('stage', models.CharField(blank=True, default='', max_length=255, verbose_name='Этап')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('archive', models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Архив')),
                ('company_data', models.JSONField(blank=True, default=dict, verbose_name='Реквизиты компании')),
                ('extracted_data', models.JSONField(blank=True, default=list, verbose_name='Извлечённые рабочие места')),
                ('output_5_1b', models.CharField(blank=True, default='', max_length=512, verbose_name='Документ 5_1б')),
                ('output_6_5', models.CharField(blank=True, default='', max_length=512, verbose_name='Документ 6_5')),
            ],
            options={
                'verbose_name': 'Батч',
                'verbose_name_plural': 'Батчи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, verbose_name='Путь в архиве')),
                ('kind', models.CharField(choices=[('card', 'Карта рабочего места'), ('perechen', 'Перечень'), ('template', 'Шаблон (заполненный эталон)'), ('pdf', 'PDF'), ('xlsx', 'Excel'), ('other', 'Прочее')], default='other', max_length=16, verbose_name='Тип')),
                ('converted_docx_path', models.CharField(blank=True, default='', max_length=1024, verbose_name='Путь к .docx')),
                ('parsed', models.BooleanField(default=False, verbose_name='Разобран')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='attestation.batch')),
            ],
            options={
                'verbose_name': 'Файл архива',
                'verbose_name_plural': 'Файлы архива',
                'ordering': ['path'],
            },
        ),
    ]
