# Generated by Django 5.1.4 on 2026-06-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='output_lang',
            field=models.CharField(choices=[('cyr', 'Кириллица'), ('lat', 'Lotin (латиница)')], default='cyr', max_length=3, verbose_name='Язык документов'),
        ),
    ]
