# Generated by Django 5.1.4 on 2026-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0002_batch_output_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='output_6_4',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Документ 6_4'),
        ),
    ]
